### PR TITLE
feat: Add support for Django 4.x

### PR DESCRIPTION
**Pull request by russell310**

### CODE REVIEW

**Comment by Tobeyforce** [comment]
Would be great if this was approved soon. Thanks for providing a solution in the meantime.

**Review by Tobeyforce — CHANGES_REQUESTED** [review]
Should also add the same import fix to serializers.py

**Comment by russell310** [comment]
@Tobeyforce fixed issues on serializers

**Review by mr-vaibh — APPROVED** [review]

**Comment by melanger** [comment]
Hi, are you doing to merge this? It would be great to have Django 4 support.

**Comment by russell310** [comment]
I've no rights to merge.

**Review by CuriousLearner — CHANGES_REQUESTED** [review]
Hey,

Thanks for your contributions, Russell.

Can you please also update the tox file including testing with Django 4?

**Comment by russell310** [comment]
@CuriousLearner updated tox file. Please check

**Review by CuriousLearner — APPROVED** [review]

**Comment by CuriousLearner** [comment]
Thank you!

Changes looks good to me. However seems like we'd need to change from travis to Github Actions CI. I'll take a look at that.

**Comment by CuriousLearner** [comment]
Thanks @russell310 

I've added your contribution in b407b60c918c189678ce85a19bc70352b591afa0

**Pull request closed without merging**
